export const cuisinesList: string[] = [
  "American",
  "BBQ",
  "Breakfast",
  "Burgers",
  "Cafe",
  "Chinese",
  "Desserts",
  "French",
  "Greek",
  "Healthy",
  "Indian",
  "Italina",
  "Japanese",
  "Mexican",
  "Noodles",
  "Organic",
  "Pasta",
  "Pizza",
  "Salads",
  "SeaFood",
  "Spanish",
  "Steak",
  "Sushi",
  "Tacos",
  "Tapas",
  "Vegan",
];

export const ORDER_STATUS = [
  { label: "Placed", value: "placed", progressValue: 0 },
  {
    label: "Awaiting restaurant confiramtion",
    value: "paid",
    progressValue: 25,
  },
  { label: "In Progress", value: "inProgress", progressValue: 50 },
  { label: "Out for delivery", value: "outForDelivery", progressValue: 75 },
  { label: "Deliverd", value: "deliverd", progressValue: 100 },
];
